[package]
name = "backtest"
version = "0.1.0"
authors = ["Jonty <jonty.morris@yahoo.co.nz>"]
edition = "2018"

[dependencies]
csv = "1.1.4"
chrono = "0.4"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
indicatif = "0.15.0"
stocks_core = { path="../stocks_core" }
