[package]
name = "stocks_core"
version = "0.1.0"
authors = ["Jonty <jonty.morris@yahoo.co.nz>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
